# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_canteen_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class AddCanteen(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 243)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 331, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setStyleSheet("font: 12pt \"黑体\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255, 0);\n"
"")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.canteenIdEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.canteenIdEdit.setObjectName("canteenIdEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.canteenIdEdit)
        self.canteenIdLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.canteenIdLabel.setObjectName("canteenIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.canteenIdLabel)
        self.canteenLocLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.canteenLocLabel.setObjectName("canteenLocLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.canteenLocLabel)
        self.canteenLocEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.canteenLocEdit.setObjectName("canteenLocEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.canteenLocEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 451, 81))
        self.label_3.setStyleSheet("border-image: url(:/png/images/login_topbg.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).clicked.connect(self.addCanteen)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).clicked.connect(self.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600;\">请输入要增加的食堂的信息</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600;\">(信息不能为空)</span></p></body></html>"))
        self.canteenIdLabel.setText(_translate("Dialog", "食堂编号："))
        self.canteenLocLabel.setText(_translate("Dialog", "食堂位置："))

    def show(self, managerId):
        self.managerId = managerId
        self.window = QtWidgets.QWidget()
        self.setupUi(self.window)
        self.window.show()

    def close(self):
        self.window.close()

    def addCanteen(self, managerId):
        canteenId = self.canteenIdEdit.text()
        canteenLoc = self.canteenLocEdit.text()
        import pymysql
        db = pymysql.connect(host="localhost",
                             user="root",
                             password="zxq1314mm",
                             database="canteen",
                             port=3306,
                             charset="utf8")
        cursor = db.cursor()
        cursor.execute("select * from canteeninfo")
        canteen_info = cursor.fetchall()
        repeat_flag = False
        for i in range(cursor.rowcount):
            if canteenId == canteen_info[i][0]:
                repeat_flag = True
        if repeat_flag:
            QMessageBox.warning(None, "食堂编号重复", "您输入的食堂编号已存在，请重新输入！", QMessageBox.Ok)
        else:
            try:
                cursor.execute("insert into canteeninfo(c_id,ma_id,c_loc) values(%s,%d,%s)",
                               [canteenId, self.managerId, canteenLoc])
                db.commit()
                self.close()
            except:
                # 发生错误时回滚
                QMessageBox.warning(None, "数据库出错", "抱歉，数据库操作出现错误，请重试！", QMessageBox.Ok)
                db.rollback()
        db.close()
import login_topbg_rc
