# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class LoginDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 289)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 565, 319))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/images/login_topbg.png"))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.loginButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setMaximumSize(QtCore.QSize(90, 30))
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_2.addWidget(self.loginButton)
        self.regButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.regButton.setMaximumSize(QtCore.QSize(90, 30))
        self.regButton.setObjectName("regButton")
        self.horizontalLayout_2.addWidget(self.regButton)
        self.exitButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.exitButton.setMaximumSize(QtCore.QSize(90, 30))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_2.addWidget(self.exitButton)
        spacerItem3 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.pwdLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.pwdLabel.setObjectName("pwdLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pwdLabel)
        self.clsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.clsLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.clsLabel.setObjectName("clsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.clsLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.comboBox.setMouseTracking(True)
        self.comboBox.setTabletTracking(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.nameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.nameEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.pwdEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.pwdEdit.setObjectName("pwdEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pwdEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.gridLayout_2.addLayout(self.formLayout, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.loginButton.clicked.connect(self.login)
        self.regButton.clicked.connect(self.register)
        self.exitButton.clicked.connect(self.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginButton.setText(_translate("Dialog", "登录"))
        self.regButton.setText(_translate("Dialog", "注册"))
        self.exitButton.setText(_translate("Dialog", "退出"))
        self.nameLabel.setText(_translate("Dialog", "用户名："))
        self.pwdLabel.setText(_translate("Dialog", "密码："))
        self.clsLabel.setText(_translate("Dialog", "用户类别："))
        self.comboBox.setItemText(0, _translate("Dialog", "普通用户"))
        self.comboBox.setItemText(1, _translate("Dialog", "食堂管理员"))
        self.comboBox.setItemText(2, _translate("Dialog", "商家"))
        self.comboBox.setItemText(3, _translate("Dialog", "派送员"))

    def login(self):
        usr_name = self.nameEdit.text()
        usr_pwd = self.pwdEdit.text()
        cls_idx = self.comboBox.currentIndex()
        cls_dict = {0: "plain", 1: "manager", 2: "merchant", 3: "courier"}
        cls = cls_dict[cls_idx]
        if len(usr_name) == 0 or len(usr_pwd) == 0:
            QMessageBox.warning(None, "用户名或密码为空", "用户名和密码不能为空！", QMessageBox.Ok)
        else:
            # 数据库操作部分
            import pymysql
            db = pymysql.connect(host="localhost",
                                 user="root",
                                 password="zxq1314mm",
                                 database="canteen",
                                 port=3306,
                                 charset="utf8")
            cursor = db.cursor()
            cursor.execute("select * from userinfo")
            usr_info = cursor.fetchall()
            db.close()
            find_name = False
            login_ok = False
            # 逐行数据查找用户名是否存在
            for i in range(cursor.rowcount):
                if usr_info[i][0] == usr_name and usr_info[i][3] == cls:
                    find_name = True
                    if usr_info[i][2] == usr_pwd:
                        login_ok = True
                        self.openUserSelCanteen()
                        break
                    else:
                        QMessageBox.warning(None, "密码错误", "您输入的密码有误，请重新输入！", QMessageBox.Ok)
            # 数据库操作结束
            if not find_name:
                QMessageBox.warning(None, "用户名不存在", "抱歉，您输入的用户名不存在，请先注册！", QMessageBox.Ok)
            elif login_ok:
                self.close()

    def register(self):
        import register_dialog
        self.register = register_dialog.RegisterDialog()
        self.register.show()

    def show(self):
        self.window = QtWidgets.QWidget()
        self.setupUi(self.window)
        self.window.show()

    def close(self):
        self.window.close()

    def openUserSelCanteen(self):
        import user_select_canteen
        self.usc = user_select_canteen.UserSelCanteen()
        self.usc.show(self.nameEdit.text())

import login_topbg_rc
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = LoginDialog()
    login.show()
    sys.exit(app.exec_())