# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class UserOrderDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(438, 344)
        Dialog.setStyleSheet("#Dialog{border-image: url(:/png/images/login_bg.png);}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeaderLabels(["菜品编号", "菜品名", "菜品口味", "菜品价格", "下单数量"])
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)

        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textBrowser.setStyleSheet("color: rgb(255, 0, 0);\n"
                                       "font: 12pt \"黑体\";\n"
                                       "background-color: rgb(255, 255, 255, 0);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.isClosed = True

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.deleteButton.setText(_translate("Dialog", "删除"))
        self.textBrowser.setHtml(_translate("Dialog",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600;\">你目前所点的菜如下</span></p></body></html>"))

    def show(self):
        self.dishes = []
        self.tableInit = False
        self.window = QtWidgets.QWidget()
        self.setupUi(self.window)
        self.window.show()
        self.isClosed = False

    def close(self):
        self.isClosed = True
        self.window.close()

    def showOrders(self):
        if not self.tableInit:
            rowcnt = len(self.dishes)
            colomncnt = len(self.dishes[0])
            self.tableWidget.setRowCount(rowcnt)
            self.tableWidget.setColumnCount(colomncnt)
            for i in range(rowcnt):
                for j in range(colomncnt):
                    data = QTableWidgetItem(self.dishes[i][j])
                    self.tableWidget.setItem(i, j, data)
            self.tableWidget.resizeColumnsToContents()
            self.tableWidget.resizeRowsToContents()
            self.tableWidget.setAlternatingRowColors(True)
            self.tableWidget.horizontalHeader().setStretchLastSection(True)

    def addOrder(self, dish):
        self.dishes.append(dish)
        self.tableWidget.setRowCount(len(self.dishes))
        for j in range(len(self.dishes[0])):
            data = QTableWidgetItem(dish[j])
            self.tableWidget.setItem(len(self.dishes)-1, j, data)

    def deleteOrder(self):
        idx = self.tableWidget.selectedItems()[0].row()
        self.dishes.pop(idx)
        self.tableWidget.removeRow(idx)

import login_bg_rc
