# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_canteen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView


class UserSelCanteen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 632)
        Form.setStyleSheet("#Form{border-image: url(:/png/images/login_bg.png);}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setStyleSheet("color: rgb(255, 0, 0);\n"
                                       "background-color: rgb(0, 0, 0, 0);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidget.setObjectName("tableWidget")

        # 从这里开始自己添加从数据库读取数据的相关内容
        import pymysql
        db = pymysql.connect(host="localhost",
                             user="root",
                             password="zxq1314mm",
                             database="canteen",
                             port=3306,
                             charset="utf8")
        # 用户可以看到食堂的编号、位置、管理员姓名与联系方式
        cursor = db.cursor()
        cursor.execute("select c_id, c_loc, ma_name, ma_phone "
                       "from canteeninfo, managerinfo "
                       "where canteeninfo.ma_id=managerinfo.ma_id")
        result = cursor.fetchall()
        row = cursor.rowcount
        if row != 0:
            vol = len(result[0])
        else:
            vol = 0
        cursor.close()
        db.close()
        # 到此是数据库交互结束部分
        # 设置表格
        self.tableWidget.setRowCount(row)
        self.tableWidget.setColumnCount(vol)
        self.tableWidget.setHorizontalHeaderLabels(["食堂编号", "食堂位置", "管理员姓名", "管理员联系方式"])
        for i in range(row):
            for j in range(vol):
                data = QTableWidgetItem(str(result[i][j]))
                self.tableWidget.setItem(i, j, data)
        self.tableWidget.resizeColumnsToContents()
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)

        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tableWidget.doubleClicked.connect(self.openSelShop)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).clicked.connect(self.openSelShop)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).clicked.connect(self.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">请选择一个食堂</span></p></body></html>"))

    def show(self, usrname):
        self.usrname = usrname
        self.window = QtWidgets.QWidget()
        self.setupUi(self.window)
        self.window.show()

    def close(self):
        self.window.close()

    def openSelShop(self):
        import user_select_shop
        id = self.tableWidget.selectedItems()[0].row()
        self.uss = user_select_shop.UserSelShop()
        self.uss.show(id)
import login_bg_rc

